name: Java CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'liberica'
          java-package: jdk+fx
          cache: maven

      - name: Install xvfb & graphics dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            xvfb \
            libgtk-3-0 \
            libglu1-mesa \
            libpango-1.0-0 \
            libasound2t64 \
            libgl1-mesa-dri \
            x11-utils

      - name: Start Xvfb virtual display
        run: |
          Xvfb :99 -screen 0 1920x1080x24 -ac +extension GLX +render -noreset &
          sleep 3
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Build and Run Tests
        env:
          DISPLAY: :99
        run: |
          mvn -B test \
            -Dprism.order=sw \
            -Dprism.verbose=false \
            -Djava.awt.headless=false \
            -Dtestfx.headless=false

      - name: Package Application
        if: success()
        run: mvn -B package -DskipTests

      - name: Archive Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: auction-system-build
          path: "**/target/*.jar"